### ISSUE TITLE
Errors trying to run numjs on npm or in jsbin

### ISSUE THREAD

**Issue by Bondifrench** [nicolaspanel/numjs#12]
Hi,

I tried to run `numjs` with [`RunKit`](https://runkit.com/npm/numjs), it gives me the following error messages:
````
Error Stack Trace Viewer 
Error: Cannot find module './build/Release/sharp.node'
at Module._resolveFilename in core module.js — line 325
at Module._load in core module.js — line 276
at Module.require in core module.js — line 353
at require in core internal/module.js — line 12
at sharp/index.js — line 12
node.js startup…
````

and when trying to use `numjs` in [jsbin](https://jsbin.com/merulanuxa/3/edit?html,js,console,output) I don't get the expected results.
It looks like it's giving me back the full constructor in the console instead of the array.

**Comment by nicolaspanel** [comment]
It is possible that runkit do not support add-ons... I don't bandwidth right now to look deeper but PR are always welcome ;) best regards

**Comment by ds604** [comment]
Hi,
I got a related error trying to install numjs from npm (the browser version worked fine for me). The problem was with sharp@0.16.2 failing.

sharp@0.17.3 installs fine for me, so changing the dependency in the package.json to "sharp": "^0.17.0" allowed numjs to install without problem. I'll send a pull request with this change, if this is causing issues for others.

**Comment by nicolaspanel** [comment]
@Bondifrench : jsbin's console do not behave like node's or chrome's console. To have a properly rendered string represetation of the array you must use `console.log(''+yourArray)` or `console.log(yourArray.toString()`.

@ds604 : updating sharp did not fix the runkit issue.
